CREATE DATABASE Registration;

CREATE TABLE Registration.user ( 
	id INTEGER(10) NOT NULL AUTO_INCREMENT, 
	nickname VARCHAR(100) NOT NULL, 
	email VARCHAR(100) NOT NULL, 
	password VARCHAR(100) NOT NULL, 
	PRIMARY KEY(id) 
	)